apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-configmap-v1
  namespace: cassandra
data:
  pre_run.sh: |-
    echo "  ** this is pre_run.sh script executed before run.sh **"
    #Examples:
    echo "Change default Authenticator & Authorizer"
    sed -ri 's/(authenticator:).*/\1 PasswordAuthenticator/' /etc/cassandra/cassandra.yaml
    sed -ri 's/(authorizer:).*/\1 CassandraAuthorizer/' /etc/cassandra/cassandra.yaml
    #test "$(hostname)" == 'cassandra-demo-dc1-rack2-0' && echo "update param" && sed -i 's/windows_timer_interval: 1/windows_timer_interval: 2/' /etc/cassandra/cassandra.yaml
    #test "$(hostname)" == 'cassandra-demo-dc1-rack3-0' && echo "-Dcassandra.replace_address_first_boot=172.31.183.209" > /etc/cassandra/jvm.options
    #test "$(hostname)" == 'cassandra-demo-dc2-rack1-0' && echo "-Dcassandra.override_decommission=true" > /etc/cassandra/jvm.options    
    echo "  ** end of pre_run.sh script, continue with run.sh **"

  post_run.sh: |-
    echo "Check Configured seeds by bootstrap"
    grep "seeds:" /etc/cassandra/cassandra.yaml
---
apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  namespace: cassandra
  labels:
    cluster: cassandra
spec:
  cassandraImage: cassandra:3.11
  bootstrapImage: orangeopensource/cassandra-bootstrap:0.1.4
  configMapName: cassandra-configmap-v1
  dataCapacity: "200Gi"
  #dataStorageClass: "gp2"
  imagepullpolicy: IfNotPresent
  imageJolokiaSecret:
    name: jolokia-auth
  hardAntiAffinity: true # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: false
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 999
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "4"
      memory: 8Gi
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        numTokens: 256
        labels:
          topology.kubernetes.io/region: eu-west-1
        rack:
          - name: rack1
            labels:
              #or we could use our custom name
              #eks.amazonaws.com/nodegroup=CassKop-AZa
              topology.kubernetes.io/zone: eu-west-1a
          - name: rack2
            labels:
              topology.kubernetes.io/zone: eu-west-1b
          - name: rack3
            labels:
              topology.kubernetes.io/zone: eu-west-1c
#UNCOMMENT FOR DEMO
#      - name: dc2
#        nodesPerRacks: 1
#        numTokens: 256
#        labels:
#          failure-domain.beta.kubernetes.io/region: europe-west1
#        rack:
#          - name: rack1
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-b
#          - name: rack2
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-c
#          - name: rack3
#            labels:
#              failure-domain.beta.kubernetes.io/zone: europe-west1-d
#
---
apiVersion: v1
kind: Secret
metadata:
  name: jolokia-auth
  namespace: cassandra
type: Opaque
data:
  password: TTBucDQ1NXcwcmQ=
  username: am9sb2tpYS11c2Vy