#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  annotations:
#    #eks.amazonaws.com/role-arn: arn:aws:iam::382076407153:role/k8s-tf-eks-Rbk9Aj5t-alb-ingress-controller
#    eks.amazonaws.com/role-arn: arn:aws:iam::382076407153:role/AlbIngressControllerStack-AlbIngressControllerStac-1XS67GDFXU2ZO
#  name: eksutils-admin-toto
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: eksutils-deployment
  labels:
    app: eksutils
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: eksutils
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: eksutils
    spec:
      containers:
      - name: eksutils
        image: allamand/eksutils:latest
        imagePullPolicy: Always
        command:
          - tail
          - -f
          - /dev/null
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: eksutils-admin
      terminationGracePeriodSeconds: 0
      securityContext:
        # IRSA projected secret need root ???
        #fsGroup: 1000
        #runAsUser: 1000
        fsGroup: 0
        runAsUser: 0
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: eksutils-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: eksutils-admin

